// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261003102005_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì gói & Thực phẩm ăn liền",
                            Description = "Mì ăn liền, phở khô, cháo gói"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu ăn",
                            Description = "Nước mắm, hạt nêm, dầu thực vật"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Nguyễn Trãi, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "45 Lê Văn Sỹ, Phường 13, Quận 3, TP. Hồ Chí Minh",
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "78 Phan Văn Trị, Phường 10, Quận Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "25 Nguyễn Kiệm, Phường 3, Quận Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Phạm Minh D",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0905678123",
                            RewardPoints = 220
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "16 Cách Mạng Tháng 8, Phường 12, Quận 10, TP. Hồ Chí Minh",
                            CustomerName = "Hoàng Thị E",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0934567890",
                            RewardPoints = 80
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "89 Lý Thường Kiệt, Phường 8, Quận 10, TP. Hồ Chí Minh",
                            CustomerName = "Võ Thành F",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0978123456",
                            RewardPoints = 35
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "32 Điện Biên Phủ, Phường 15, Quận Bình Thạnh, TP. Hồ Chí Minh",
                            CustomerName = "Đặng Ngọc G",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0909876543",
                            RewardPoints = 310
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "71 Quang Trung, Phường 10, Quận Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Bùi Thị H",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 65
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "15 Võ Văn Tần, Phường 6, Quận 3, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Hoàng I",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0987654321",
                            RewardPoints = 125
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "48 Nguyễn Văn Cừ, Phường 2, Quận 5, TP. Hồ Chí Minh",
                            CustomerName = "Lâm Thị K",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0903456789",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "62 Âu Cơ, Phường 9, Quận Tân Bình, TP. Hồ Chí Minh",
                            CustomerName = "Trương Văn L",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0931234567",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "105 Lạc Long Quân, Phường 3, Quận 11, TP. Hồ Chí Minh",
                            CustomerName = "Phan Thị M",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0964567890",
                            RewardPoints = 55
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "27 Phạm Văn Đồng, Phường 3, TP. Thủ Đức, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Đức N",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0973456123",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "39 Kha Vạn Cân, Phường Linh Tây, TP. Thủ Đức, TP. Hồ Chí Minh",
                            CustomerName = "Lê Thị O",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0906789123",
                            RewardPoints = 240
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "88 Nguyễn Oanh, Phường 17, Quận Gò Vấp, TP. Hồ Chí Minh",
                            CustomerName = "Phạm Quốc P",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0915678901",
                            RewardPoints = 95
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "12 Trường Chinh, Phường 13, Quận Tân Bình, TP. Hồ Chí Minh",
                            CustomerName = "Đỗ Minh Q",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0981234567",
                            RewardPoints = 45
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "54 Nguyễn Thị Minh Khai, Phường Đa Kao, Quận 1, TP. Hồ Chí Minh",
                            CustomerName = "Nguyễn Thị R",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0907891234",
                            RewardPoints = 275
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "76 Hoàng Văn Thụ, Phường 9, Quận Phú Nhuận, TP. Hồ Chí Minh",
                            CustomerName = "Huỳnh Văn S",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0937894561",
                            RewardPoints = 70
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "41 Phan Đăng Lưu, Phường 3, Quận Bình Thạnh, TP. Hồ Chí Minh",
                            CustomerName = "Mai Thị T",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0967891234",
                            RewardPoints = 20
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "93 Nguyễn Văn Luông, Phường 12, Quận 6, TP. Hồ Chí Minh",
                            CustomerName = "Đinh Văn U",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0976543210",
                            RewardPoints = 160
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "SP001",
                            CategoryId = 1,
                            Price = 15000m,
                            ProductName = "Bánh Oreo",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "SP002",
                            CategoryId = 1,
                            Price = 45000m,
                            ProductName = "Bánh Chocopie",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "SP003",
                            CategoryId = 1,
                            Price = 25000m,
                            ProductName = "Kẹo dẻo trái cây",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "SP004",
                            CategoryId = 1,
                            Price = 12000m,
                            ProductName = "Snack khoai tây",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "SP005",
                            CategoryId = 1,
                            Price = 28000m,
                            ProductName = "Bánh mì sandwich",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "SP006",
                            CategoryId = 1,
                            Price = 18000m,
                            ProductName = "Kẹo bạc hà",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "SP007",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Coca Cola",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "SP008",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Pepsi",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "SP009",
                            CategoryId = 2,
                            Price = 15000m,
                            ProductName = "Trà đào",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "SP010",
                            CategoryId = 2,
                            Price = 7000m,
                            ProductName = "Nước suối Aquafina",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "SP011",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Sting dâu",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "SP012",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Trà xanh 0 độ",
                            StockQuantity = 85
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "SP013",
                            CategoryId = 3,
                            Price = 8000m,
                            ProductName = "Sữa tươi Vinamilk",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "SP014",
                            CategoryId = 3,
                            Price = 7000m,
                            ProductName = "Sữa chua Vinamilk",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "SP015",
                            CategoryId = 3,
                            Price = 25000m,
                            ProductName = "Sữa đặc Ông Thọ",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "SP016",
                            CategoryId = 3,
                            Price = 35000m,
                            ProductName = "Phô mai Con Bò Cười",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "SP017",
                            CategoryId = 3,
                            Price = 9000m,
                            ProductName = "Sữa Milo",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "SP018",
                            CategoryId = 3,
                            Price = 7000m,
                            ProductName = "Sữa đậu nành Fami",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "SP019",
                            CategoryId = 4,
                            Price = 5000m,
                            ProductName = "Mì Hảo Hảo",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "SP020",
                            CategoryId = 4,
                            Price = 10000m,
                            ProductName = "Mì Omachi",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 21,
                            Barcode = "SP021",
                            CategoryId = 4,
                            Price = 12000m,
                            ProductName = "Phở bò ăn liền",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 22,
                            Barcode = "SP022",
                            CategoryId = 4,
                            Price = 10000m,
                            ProductName = "Cháo thịt bằm",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 23,
                            Barcode = "SP023",
                            CategoryId = 4,
                            Price = 9000m,
                            ProductName = "Miến gà ăn liền",
                            StockQuantity = 65
                        },
                        new
                        {
                            ProductId = 24,
                            Barcode = "SP024",
                            CategoryId = 4,
                            Price = 6000m,
                            ProductName = "Mì xào bò",
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 25,
                            Barcode = "SP025",
                            CategoryId = 5,
                            Price = 32000m,
                            ProductName = "Nước mắm Nam Ngư",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 26,
                            Barcode = "SP026",
                            CategoryId = 5,
                            Price = 45000m,
                            ProductName = "Dầu ăn Simply",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 27,
                            Barcode = "SP027",
                            CategoryId = 5,
                            Price = 30000m,
                            ProductName = "Hạt nêm Knorr",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 28,
                            Barcode = "SP028",
                            CategoryId = 5,
                            Price = 22000m,
                            ProductName = "Tiêu xay",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 29,
                            Barcode = "SP029",
                            CategoryId = 5,
                            Price = 22000m,
                            ProductName = "Đường trắng",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 30,
                            Barcode = "SP030",
                            CategoryId = 5,
                            Price = 10000m,
                            ProductName = "Muối i-ốt",
                            StockQuantity = 70
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
